coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%

fixes:
  - "build/::src/"  # Map build/ paths to src/ paths
ignore:
  - "build/tests/**"
  - "**/*.test.js"
  - "node_modules/**/*"
  - "coverage/**/*"